image: anapsix/alpine-java:8_jdk

before_script:
  - which java
  - which javac

stages:
  - build
  - deploy
  - manual_deploy

build:
  stage: build
  before_script:
    - ./gradlew setupCiWorkspace
    - ./gradlew ciWriteBuildNumber
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month


